//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessment7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public int GuestID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public string EmailAddress { get; set; }
        public string Guest1 { get; set; }
    }
}
